version: '3'

######### Services ###################################

services:
  elasticsearch:
    build:
      context: docker/elasticSearch
      dockerfile: Dockerfile
    container_name: elasticsearch_playground
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=password
    depends_on:
      - elasticsearch
    restart: always

######### Volumes ###################################

volumes:
  database:
    driver: local